#!/bin/sh
LOGTIME=`date +"%Y-%m-%d %H:%M:%S"`
LOGFILE=/var/log/ddns-check.log
DDNSBIN=/usr/bin/ddns-up
YMD=`date +%Y%m%d-%H`

# Log rotation.
[ $(echo "`du $LOGFILE | awk '{ print $1 }'` > 4096" | bc) -ne 0 ] &&
tar -czf $LOGFILE-$YMD.tar.gz $LOGFILE && rm $LOGFILE && touch $LOGFILE &&
echo "$LOGTIME: Last log file was too big (>4M), compressed for archive and creating a new one." >> $LOGFILE 

ps up `cat /tmp/ddns.pid ` > /dev/null
ecode=$?
if [ $ecode -eq 0 ]; then
    echo "DDNS daemon checked: $LOGTIME, Status: Running" >> $LOGFILE
    exit 0
else
    [ -f /tmp/ddns.pid ] && rm /tmp/ddns.pid
    echo "DDNS daemon checked: $LOGTIME, Status: Not running" >> $LOGFILE
    $DDNSBIN
fi
