#!/bin/bash
LOGFILE=/var/log/ddns-check.log
DDNSBIN=/usr/bin/ddns-up
PIDFILE=/var/run/ddns.pid
YMD=$(date +%Y%m%d-%H)

logtime() { date +"%Y-%m-%d %H:%M:%S"; }

ps up "$(cat $PIDFILE)" &> /dev/null
if [ $? -eq 0 ]; then
    echo "DDNS daemon checked: $(logtime), Status: Running" >> $LOGFILE
    exit 0
else
    echo "DDNS daemon checked: $(logtime), Status: Not running" >> $LOGFILE
    $DDNSBIN
fi
