#!/bin/bash
LOGFILE=/var/log/ddns-check.log
DDNSBIN=/usr/bin/ddns-up
PIDFILE=/var/run/ddns.pid
YMD=$(date +%Y%m%d-%H)

logtime() { date +"%Y-%m-%d %H:%M:%S"; }

# Log rotation.
[ "$(echo "$(du $LOGFILE | awk '{ print $1 }') > 4096" | bc)" -ne 0 ] &&
tar -czf $LOGFILE-"$YMD".tar.gz $LOGFILE && rm $LOGFILE && touch $LOGFILE &&
echo "$(logtime): Last log file was too big (>4M), compressed for archive and creating a new one." >> $LOGFILE 

ps up "$(cat $PIDFILE)" &> /dev/null
if [ $? -eq 0 ]; then
    echo "DDNS daemon checked: $(logtime), Status: Running" >> $LOGFILE
    exit 0
else
    echo "DDNS daemon checked: $(logtime), Status: Not running" >> $LOGFILE
    $DDNSBIN
fi
