#!/bin/bash
[ -z $1 ] && echo "Usage: $(basename $0) devices" && exit

timeconv()
{
  x=$1
  date -d "1970-01-01 UTC+8 +$x seconds" +"%Hh %Mm %Ss"
}

workdir=~/aokp
D=$(LC_ALL=C date +%Y-%m-%d)
backupdir=~/builds
remotedir=/var/www/aokp
remote=username@hostname
logdir=~/make-logs
logfile=$D.log
buildlog=buildlog-$(date +%Y%m%d-%H%M%S).log
#export OUT_DIR_COMMON_BASE=/tmp

if [ -z $OUT_DIR_COMMON_BASE ]; then
  outdir=$workdir/out/target/product
else
  [ ! -d $OUT_DIR_COMMON_BASE ] && echo "Defined OUT_DIR_COMMON_BASE doesn't exist. Please check script." && exit 1
  outdir=$OUT_DIR_COMMON_BASE/aokp/target/product
  [ -d $OUT_DIR_COMMON_BASE/aokp ] && rm -rf $OUT_DIR_COMMON_BASE/aokp
fi

for dirs in $workdir $backupdir $logdir; do
  [ ! -d $dirs ] && echo "Defined directory $dirs doesn't exist. Please check script or create the directory."
  exit 1
done

ssh $remote exit
[ $? -ne 0 ] && echo "Connection to $remote failed. Please check host setting in script."

ssh $remote "ls $remotedir &> /dev/null"
[ $? -ne 0 ] && echo "Cannot access $remotedir on $remote. Please check settings in script."

for dir in $backupdir $logdir; do
  [ ! -d $dir ] && mkdir -p $dir
done

echo "Making AOKP for $# devices: $@"
echo "Building from directory: $workdir"
echo "Builds will be saved to: $backupdir"
echo "Builds will be uploaded to: $remote:$remotedir"
echo "Build log will be found at: $logdir, filename is $buildlog"
echo "Time consumption for the process will be logged at: $logdir/$logfile"
[ ! -z $OUT_DIR_COMMON_BASE ] && echo "Build output directory has been redirected to: $OUT_DIR_COMMON_BASE"
sleep 5

cd $workdir
. $workdir/build/envsetup.sh

make clean

start=$(date +%s)

for target in $@; do
  singlestart=$(date +%s)
  brunch $target 2>&1 | tee -a $logdir/$buildlog
  singlestop=$(date +%s)
  if [ ${PIPESTATUS[0]} -ne 0 ]; then
    echo "Build error. Please check log."
    echo "Time wasted: $(timeconv $((singlestop - start)))"
    exit 1
  fi
  targetzip=aokp_$target\_jb-mr2_unofficial_$D.zip
  cp $outdir/$target/$targetzip ~/builds/
  echo "$target: $(timeconv $((singlestop - singlestart)))" | tee -a $logdir/$logfile
  rsync -avzP $backupdir/$targetzip $remote:$remotedir/ &
  upload_pids="$upload_pids $!"
done

for process in $upload_pids; do
  wait $process > /dev/null 2>&1
done

ssh $remote "[ -f $remotedir/md5.txt ] && rm $remotedir/md5.txt; md5sum $remotedir/*.zip | sed s#$remotedir/#file:\ # > $remotedir/md5.txt; chown www-data: $remotedir/*" > /dev/null 2>&1

stop=$(date +%s)
total=$((stop - start))

echo -e "Total time: $(timeconv $total)\n" | tee -a $logdir/$logfile
cat $logdir/$logfile
