#!/bin/bash
D=$(LC_ALL=C date +%Y-%m-%d)
builddir=~/builds
pushfile=aokp_$1\_jb-mr2_unofficial_$D.zip

ps aux | grep adb | grep server &> /dev/null
[ $? -ne 0 ] && sudo adb start-server

cd $builddir/
if [ "$1" = "yuga" ]
then
	adb push $pushfile /ext_card/
else
	adb push $pushfile /sdcard/
fi
